# Generated by Django 2.2.3 on 2019-11-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_profile',
            new_name='profile',
        ),
    ]
